export const FETCH_PRODUCT_START = "FETCH_PRODUCT_START";
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";
export const FETCH_PRODUCT_FAIL = "FETCH_PRODUCT_FAIL";

export const FETCH_ADDON_START = "FETCH_ADDON_START";
export const FETCH_ADDON_SUCCESS = "FETCH_ADDON_SUCCESS";
export const FETCH_ADDON_FAIL = "FETCH_ADDON_FAIL";

export const ADD_CART = "ADD_CART";
export const REMOVE_CART = "REMOVE_CART";
export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const EMPTY_CART = "EMPTY_CART";

export const ADD_CART_BUTTON = "ADD_CART_BUTTON";
export const REMOVE_CART_BUTTON = "REMOVE_CART_BUTTON";
export const REMOVE_CART_BUTTON1 = "REMOVE_CART_BUTTON1";

export const FETCH_COUPON_START = "FETCH_COUPON_START";
export const FETCH_COUPON_SUCCESS = "FETCH_COUPON_SUCCESS";
export const FETCH_COUPON_FAIL = "FETCH_COUPON_FAIL";
